wiki_files=(
    "AppFiltering"
    "AppPlan"
    "AppPlanSpec"
    "AppVersion"
    "AppVersionNew"
    "BackendPrograms"
    "BasicApi"
    "BetaTest"
    "BoincFiles"
    "CloudServer"
    "CodeSigning"
    "CompileApp"
    "DataBase"
    "DeleteFile"
    "DesktopGrid"
    "ExampleApps"
    "FileCompression"
    "GraphicsApi"
    "GraphicsApps"
    "HomogeneousRedundancy"
    "HTMLGfx"
    "HtmlOps"
    "IntermediateUpload"
    "JobEst"
    "JobIn"
    "JobStage"
    "JobSubmission"
    "JobTemplates"
    "KeySetup"
    "LocalityNew"
    "LocalityScheduling"
    "MakeProject"
    "MultiHost"
    "PlanClassFunc"
    "ProfileScreen"
    "ProjectConfigFile"
    "ProjectOptions"
    "ServerComponents"
    "ServerIntro"
    "SourceCodeGit"
    "VboxApps"
    "VolunteerComputing"
    "WorkGeneration"
    "XmlFormat"
)

for wiki_file in "${wiki_files[@]}"
do
    if [ ! -f "/c/Users/Vitalii.Koshura/Downloads/${wiki_file}.txt" ]; then
        echo "Downloading ${wiki_file}..."
        curl -o "/c/Users/Vitalii.Koshura/Downloads/${wiki_file}.txt" "https://boinc.berkeley.edu/trac/wiki/${wiki_file}?format=txt"
    fi
    python "./wiki2md.py" "/c/Users/Vitalii.Koshura/Downloads/${wiki_file}.txt" "/c/SRC/Other/boinc.wiki/${wiki_file}.md"
done
